Commit for backup after trying button library
Currently using button.cpp as base function,
and called on input.cpp as onButtonPressed function

NOTE:
*xirkabit will hang shortly after button is pressed and handled

* In block mode programing, the name is not indetical,
it should be "A" instead of "button A"

*sim still error:
pxsim.pins.digitalWritePin is not a function